# Dependencies
markdown:         kramdown
pygments:         true

# Permalinks
permalink:        pretty

# Server
destination:      ./_gh_pages
exclude:          [".editorconfig", ".gitignore", ".ruby-version", "bower.json", "composer.json", "CNAME", "Gruntfile.js", "LICENSE", "package.json", "node_modules", "README.md", "less"]
port:             9090

# Custom vars - markdown.jp
name:             日本語Markdownユーザー会
googlegroup_link: https://groups.google.com/d/forum/markdown-ja
trello_link:      https://trello.com/b/74KojBBd/markdown-markdown-ja
github_link:      https://github.com/markdown-ja/markdown.jp
